# Generated by Django 5.0.1 on 2024-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0006_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('in-cart', 'in-cart'), ('order-places', 'order-places'), ('cancelled', 'cancelled')], default='in-cart', max_length=100),
        ),
    ]
