# Generated by Django 5.0.1 on 2024-01-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_placeorder_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='cart',
        ),
    ]
